version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pzk#219441'
      MARIADB_DATABASE: 'kanayama'
      MYSQL_USER: 'sospet'
      MYSQL_PASSWORD: 'sospet@2300'
    ports:
      - "3306:3306"
    volumes:
      - .\mysql_data:/var/lib/mysql
